server:
  port: 5010
spring:
  application:
    name: login-safety
    cloud:
      nacos:
        discovery:
          server-addr: 192.168.137.189:8848

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.201.196:3306/db_stu_sys?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: qycssg!0
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 100
mybatis-plus:
  mapper-locations: classpath:static/mybatis/mapper/*.xml

#  暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"